### ISSUE TITLE
テストコード

### ISSUE THREAD

**Issue by sinnershiki** [sinnershiki/hubot-ritsbus#10]
スクレイピングまわりはテスト書いた方がいいかなあ

**Comment by pgmot** [comment]
今のhtmlをテストデータとして落としておいてそれが想定通りにパースされるかチェックすれば良さそう

**Comment by sinnershiki** [comment]
なるほどね！

**Comment by pgmot** [comment]
少なくともテストするときにwebページ叩くのは野蛮人の行為だから
